# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50bfefe60348f36b16a43a9823c746db50050c77d585c31020ffc15b5b183ee0d25c02fa1534f5f2581c770e0d46a1113892c9c73f296f6dabad930955f5e10a

test:
  secret_key_base: d90ce2d440ab4a77d9b1de5765a9a7c464d83b2013ca6c7ba3b3ac3944c4f2c52176ae9f1eca4b378cff76894787e66d293f1c1819f4a8c8fb6d0068885bed4f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
